recipe_db/config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'recipes/index'
  get 'pages/about'
  get 'pages/dinner'
  get 'pages/lunch'
  get 'pages/breakfast'
  get 'pages/italian'
  get 'pages/american'
  get 'pages/greek'
  
  
end

recipe_db/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

recipe_db/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

recipe_db/app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, dependent: :destroy
    accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

    has_many :steps, dependent: :destroy
    accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

    mount_uploader :image, ImageUploader

    
end

recipe_db/app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

recipe_db/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

recipe_db/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end

    def home
    end
    
    def dinner
        @recipes = Recipe.where(:mealTime => 'Dinner')
    end

    def lunch
        @recipes = Recipe.where(:mealTime => 'Lunch')
    end

    def breakfast
        @recipes = Recipe.where(:mealTime => 'Breakfast')
    end

    def italian
        @recipes = Recipe.where(:mealType => 'Italian')
    end

    def american
        @recipes = Recipe.where(:mealType => 'American')
    end

    def greek
        @recipes = Recipe.where(:mealType => 'Greek')
    end
end

recipe_db/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:mealTime, :remove_image, :image, :title, :description, :mealType, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy])
    end
end

recipe_db/app/helpers/application_helper.rb
module ApplicationHelper
end

recipe_db/app/helpers/pages_helper.rb
module PagesHelper
end

recipe_db/app/helpers/recipes_helper.rb
module RecipesHelper
end

recipe_db/app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
</footer>

recipe_db/app/views/layouts/_header.html.erb
<!--
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
   <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
     <ul class="navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Recipes",recipes_path %></li>
      <li><%= link_to "About", pages_about_path %></li>
    </ul>
     </div>
   </div>
  </nav>
-->

  <nav class="navbar sticky-top navbar-dark bg-dark navbar-expand-lg">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home   </span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/recipes">Recipes   </span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages/about">About   <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Cuisines
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/pages/american">American</a>
          <a class="dropdown-item" href="/pages/italian">Italian</a>
          <a class="dropdown-item" href="/pages/greek">Greek</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/pages/breakfast">Breakfast</a>
          <a class="dropdown-item" href="/pages/lunch">Lunch</a>
          <a class="dropdown-item" href="/pages/dinner">Dinner</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

recipe_db/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

</html>

recipe_db/app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</style>
</head>

<body>
<div class="about-image">
  <div class="hero-text">
    <h1 style="font-size:50px">Our Story</h1>
  </div>
</div>

</body>
</html>

recipe_db/app/views/pages/american.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: helvetica;
    color: white;
  }
</style>

<div class="recipe-image img-responsive">

  <div class="container text-center">
    <br>
    <h1>All American Recipes</h1>
    <br>
  </div>

<div class="row d-flex justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
        <ul>
            <li><%= recipe.title %></li>
            <li><%= recipe.description %></li>
            <li><%= recipe.mealType %></li>
            <li><%= recipe.mealTime %></li>
            <div>                        
            <li><%= link_to 'Show', recipe, :class => "btn btn-light"  %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => "btn btn-light"  %>
            <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></li>
            </div>
            
        </ul>
      </div><!-- /recipe-box-->
      </div><!--col-md-4-->
    <% end %>
</div> <!--/row-->

  <div class="row justify-content-center">
    <a href="/recipes/new" class="btn btn-light btn-lg" role="button" aria-disabled="true">Create New Recipe</a>
  </div>
  <br>

</div> <!-- background images -->




recipe_db/app/views/pages/breakfast.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: helvetica;
    color: white;
  }
</style>

<div class="recipe-image img-responsive">

  <div class="container text-center">
    <br>
    <h1>All Breakfast Recipes</h1>
    <br>
  </div>

<div class="row d-flex justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
        <ul>
            <li><%= recipe.title %></li>
            <li><%= recipe.description %></li>
            <li><%= recipe.mealType %></li>
            <li><%= recipe.mealTime %></li>
            <div>                        
            <li><%= link_to 'Show', recipe, :class => "btn btn-light"  %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => "btn btn-light"  %>
            <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></li>
            </div>
            
        </ul>
      </div><!-- /recipe-box-->
      </div><!--col-md-4-->
    <% end %>
</div> <!--/row-->

  <div class="row justify-content-center">
    <a href="/recipes/new" class="btn btn-light btn-lg" role="button" aria-disabled="true">Create New Recipe</a>
  </div>
  <br>

</div> <!-- background images -->




recipe_db/app/views/pages/dinner.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: helvetica;
    color: white;
  }
</style>

<div class="recipe-image img-responsive">

  <div class="container text-center">
    <br>
    <h1>All Dinner Recipes</h1>
    <br>
  </div>

<div class="row d-flex justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
        <ul>
            <li><%= recipe.title %></li>
            <li><%= recipe.description %></li>
            <li><%= recipe.mealType %></li>
            <li><%= recipe.mealTime %></li>
            <div>                        
            <li><%= link_to 'Show', recipe, :class => "btn btn-light"  %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => "btn btn-light"  %>
            <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></li>
            </div>
            
        </ul>
      </div><!-- /recipe-box-->
      </div><!--col-md-4-->
    <% end %>
</div> <!--/row-->

  <div class="row justify-content-center">
    <a href="/recipes/new" class="btn btn-light btn-lg" role="button" aria-disabled="true">Create New Recipe</a>
  </div>
  <br>

</div> <!-- background images -->




recipe_db/app/views/pages/greek.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: helvetica;
    color: white;
  }
</style>

<div class="recipe-image img-responsive">

  <div class="container text-center">
    <br>
    <h1>All Greek Recipes</h1>
    <br>
  </div>

<div class="row d-flex justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
        <ul>
            <li><%= recipe.title %></li>
            <li><%= recipe.description %></li>
            <li><%= recipe.mealType %></li>
            <li><%= recipe.mealTime %></li>
            <div>                        
            <li><%= link_to 'Show', recipe, :class => "btn btn-light"  %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => "btn btn-light"  %>
            <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></li>
            </div>
            
        </ul>
      </div><!-- /recipe-box-->
      </div><!--col-md-4-->
    <% end %>
</div> <!--/row-->

  <div class="row justify-content-center">
    <a href="/recipes/new" class="btn btn-light btn-lg" role="button" aria-disabled="true">Create New Recipe</a>
  </div>
  <br>

</div> <!-- background images -->




recipe_db/app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}



</style>
</head>

<body>
<div class="home-image">
  <div class="hero-text">
    <h1 style="font-size:50px", font-family="Helvetica">Welcome to Your Personal Cook Book</h1>
  </div>
</div>

</body>
</html>

recipe_db/app/views/pages/italian.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: helvetica;
    color: white;
  }
</style>

<div class="recipe-image img-responsive">

  <div class="container text-center">
    <br>
    <h1>All Italian Recipes</h1>
    <br>
  </div>

<div class="row d-flex justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
        <ul>
            <li><%= recipe.title %></li>
            <li><%= recipe.description %></li>
            <li><%= recipe.mealType %></li>
            <li><%= recipe.mealTime %></li>
            <div>                        
            <li><%= link_to 'Show', recipe, :class => "btn btn-light"  %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => "btn btn-light"  %>
            <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></li>
            </div>
            
        </ul>
      </div><!-- /recipe-box-->
      </div><!--col-md-4-->
    <% end %>
</div> <!--/row-->

  <div class="row justify-content-center">
    <a href="/recipes/new" class="btn btn-light btn-lg" role="button" aria-disabled="true">Create New Recipe</a>
  </div>
  <br>

</div> <!-- background images -->




recipe_db/app/views/pages/lunch.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: helvetica;
    color: white;
  }
</style>

<div class="recipe-image img-responsive">

  <div class="container text-center">
    <br>
    <h1>All Lunch Recipes</h1>
    <br>
  </div>

<div class="row d-flex justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
        <ul>
            <li><%= recipe.title %></li>
            <li><%= recipe.description %></li>
            <li><%= recipe.mealType %></li>
            <li><%= recipe.mealTime %></li>
            <div>                        
            <li><%= link_to 'Show', recipe, :class => "btn btn-light"  %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => "btn btn-light"  %>
            <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></li>
            </div>
            
        </ul>
      </div><!-- /recipe-box-->
      </div><!--col-md-4-->
    <% end %>
</div> <!--/row-->

  <div class="row justify-content-center">
    <a href="/recipes/new" class="btn btn-light btn-lg" role="button" aria-disabled="true">Create New Recipe</a>
  </div>
  <br>

</div> <!-- background images -->




recipe_db/app/views/recipes/_form.html.erb
<style>
/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {   
  float: left;
  width: 50%;
  height: 100%%
}
.rightcolumn{
  float: right;
  width: 50%;
  height: 100%%
}
}
</style>

<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<!-- creating a space in the html for the image that will be uploaded-->
<div class="leftcolumn">
  <% if @recipe.image? %>
    <%= image_tag @recipe.image.url, class: "recipe-show" %>
    <!-- allows the user to remove the uploaded image-->
    <%= form.check_box :remove_image, :class => "btn btn-secondary btn-sml" %>
      Remove Image
    <%end%>
  <div class="row justify-content-center">
    <%= form.file_field :image, :class => "btn btn-secondary btn-sml" %>
  </div>
  <!-- if there is an image/file uploaded display it-->
</div>

<div class="rightcolumn">
  <div class="custom-control center">
    <%= form.label :title %>
    <%= form.text_field :title%>
  </div>
  <br>

  <div class="custom-control">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <br>

  <!--getting the meal type-->
  <div class="custom-control custom-radio">
    <h3>Type of Cuisine</h3>
    <%= form.label :mealType, "American", :mealType => "American"  %>
    <%= form.radio_button :mealType, "American", :checked => true %>
    <%= form.label :mealType, "Italian", :mealType => "Italian" %>
    <%= form.radio_button :mealType, "Italian" %>
    <%= form.label :mealType, "Greek", :mealType => "Greek" %>
    <%= form.radio_button :mealType, "Greek" %>
  </div>
  <br>

  <!--getting the meal time-->
  <div class="custom-control custom-radio">
    <h3>Meal Time</h3>
    <%= form.label :mealTime, "Breakfast", :mealTime => "Breakfast"  %>
    <%= form.radio_button :mealTime, "Breakfast", :checked => true %>
    <%= form.label :mealTime, "Lunch", :mealTime => "Lunch" %>
    <%= form.radio_button :mealTime, "Lunch" %>
    <%= form.label :mealTime, "Dinner", :mealTime => "Dinner" %>
    <%= form.radio_button :mealTime, "Dinner" %>
  </div>
  <br>

  <div class="custom-control">
    <h3>Add Ingredients</h3>
      <%= form.fields_for :ingredients do |ingredient| %>
        <%= render 'ingredient_fields', f: ingredient %>
      <% end %>
      <div class="links">
        <%= link_to_add_association "Add Ingredient", form, :ingredients, :class => "btn btn-secondary btn-sml" %>
        <br>
      </div>
  </div>
  <div class="custom-control">
    <h3>Add Steps</h3>
      <%= form.fields_for :steps do |step| %>
        <%= render 'step_fields', f: step %>
      <% end %>
      <div>
        <%= link_to_add_association "Add Step", form, :steps, :class => "btn btn-secondary btn-sml" %>
      </div>
      <br>
    </div>

  <div class="actions row justify-content-center">
    <%= form.submit :class => "btn btn-secondary btn-sml" %>
  </div>
<% end %>
</div>

recipe_db/app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :content, "Ingredient" %>
        <%= f.text_field :content %>
        <%= link_to_remove_association "Remove Ingredient", f %>
    </div><!-- field -->
</div><!-- nested fields -->

recipe_db/app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :direction, "Direction"%>
        <%= f.text_field :direction %>
        <%= link_to_remove_association "Remove Step", f %>
    </div><!-- field -->
</div><!-- nested fields -->

recipe_db/app/views/recipes/edit.html.erb
<style>
    h1 {
        text-align: center;
        font-size: 30px;
        font-weight: bold;
        font-family: helvetica;
    }
</style>
<header>
    <br>
    <h1>Editing Recipe</h1>
    <br>
</header>
<body>
    <%= render 'form', recipe: @recipe %>

    <%= link_to 'Show', @recipe, :class => "btn btn-secondary btn-sml row justify-content-center"%>
    <%= link_to 'Back', recipes_path, :class => "btn btn-secondary btn-smlrow justify-content-center"%>
    <br>
</body>
<footer>
    <br><br><br><br>
</footer>

recipe_db/app/views/recipes/index.html.erb
<style>
  h1 {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    font-family: helvetica;
    color: white;
  }
</style>

<div class="recipe-image">

  <div class="container text-center">
    <br>
    <h1>All Recipes</h1>
    <br>
  </div>

<div class="row d-flex justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
        <ul>
            <li><%= recipe.title %></li>
            <li><%= recipe.description %></li>
            <li><%= recipe.mealType %></li>
            <li><%= recipe.mealTime %></li>
            <div>                        
            <li><%= link_to 'Show', recipe, :class => "btn btn-light"  %>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class => "btn btn-light"  %>
            <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light"  %></li>
            </div>
            
        </ul>
      </div><!-- /recipe-box-->
      </div><!--col-md-4-->
    <% end %>
</div> <!--/row-->
  
  <br>
  <div class="row justify-content-center">
    <a href="/recipes/new" class="btn btn-light btn-lg" role="button" aria-disabled="true">Create New Recipe</a>
  </div>
  <br>

</div> <!-- background images -->

recipe_db/app/views/recipes/new.html.erb
<body>

<h1 class="justify-content-center", style="font-size:50px">New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

</body>

recipe_db/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p> 

<!-- actually displaying the image on the page, if it's there --> 
<% if @recipe.image? %>
  <%= image_tag @recipe.image.url, class: "recipe-show recipe-container"%>
<%end%>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.mealType %>
</p>

<p>
  <strong>Meal Time:</strong>
  <%= @recipe.mealTime%>
</p>

<h3>Ingredients</h3>
  <ul>
    <% for @ingredient in @recipe.ingredients %>
      <li> 
        <%= @ingredient.content %>
      </li>
    <% end %>
  </ul>

<h3>Steps</h3>
  <ol>
    <% for @step in @recipe.steps %>
      <li><%= @step.direction %></li>
    <% end %>
  </ol>
<div class="row justify-content-center">
  <%= link_to 'Edit', edit_recipe_path(@recipe), :class => "btn btn-light btn-lg"   %>
  <a href="/recipes" class="btn btn-light btn-lg" role="button" aria-disabled="true">Back</a>
</div>